### ISSUE TITLE
Need to use screen area mode wisely

### ISSUE THREAD

**Issue by devbotas** [tevux-tech/bhd#17]
Currently, there's lot of white space, which does no good. It is extremely apparent on small screens, like Raspberry Pi 7" LCD. For example:

![image](https://user-images.githubusercontent.com/71982803/124232890-ea366c80-db1a-11eb-82d2-2bdfc9eb287c.png)
![image](https://user-images.githubusercontent.com/71982803/124232921-f3273e00-db1a-11eb-982b-97e868fc3e3d.png)

So, in reality, only about 3-5 controls fit onto the screen, which results in a lot of scrolling and general inconvenience. Especially for such a show-it-all app like BHD.

My suggestions:
* Drastically reduce margins and padding for _everything_.
* Use (if possible) an adaptive reflow, instead of fixing layout to three columns.

**Comment by Girdauskas** [comment]
I think this is solved with new design.
