### ISSUE TITLE
If a single Device publishes $state message, entire tree is rebuilt

### ISSUE THREAD

**Issue by devbotas** [tevux-tech/bhd#18]
Which is a problem for the following reasons:
* All devices switch to the first tab, even if another was selected;
* Order of devices sometimes is reshuffled, depending of I don't know what.
* Browser scrolls to another device (or maybe sometimes not).

This quickly becomes a headache if number of devices increases above 3 or so.

Refreshing _only those_ devices that actually got a $state message would certainly help a lot in usability.

Also, it would be good to refresh GUI if the $state actually changes.

**Comment by Girdauskas** [comment]
I think this is solved with "Rescan" button in new design.
