### ISSUE TITLE
Add a way to refresh controls without on a Raspberry Pi touchscreen

### ISSUE THREAD

**Issue by devbotas** [tevux-tech/bhd#2]
If BHD runs in kiosk mode on a RPI display, there's no way to refresh the controls:
- no keyboard to hit F5;
- no way to quit full-screen mode to click reload button.

So maybe a hamburger menu with a "Rescan" button? Or better yet, maybe BHD should rebuild the tree once a "homie/xxx/$homie" topic arrives?

**Comment by Girdauskas** [comment]
UI now automatically rebuilds after each $state = ready message.
