### ISSUE TITLE
Add Device state indication

### ISSUE THREAD

**Issue by devbotas** [tevux-tech/bhd#4]
Maybe here?
![image](https://user-images.githubusercontent.com/71982803/116660958-6639fa00-a99c-11eb-9d32-66ef4712fd4a.png)

**Comment by devbotas** [comment]
This works now when going from "lost" to "ready" states, but not the other way round.

**Comment by Girdauskas** [comment]
This should fix it https://github.com/devbotas/yet-another-homie-implementation/pull/3
